name: PHP Composer

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-version }}${{ matrix.run-tests && ' (tests)' || ' (syntax)' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        # PHPUnit only runs on PHP >=8.4, so only run tests on those versions.
        # For other versions, we'll run PHP syntax checks.
        include:
          - { php-version: '8.0', run-tests: false }
          - { php-version: '8.1', run-tests: false }
          - { php-version: '8.2', run-tests: false }
          - { php-version: '8.3', run-tests: false }
          - { php-version: '8.4', run-tests: true }
          - { php-version: '8.5', run-tests: true }

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      # If we're not running tests, remove the Composer requirement for PHPUnit.
      # The configured PHPUnit requires PHP >=8.4, but our library supports PHP
      # >=8.0. We can't use Composer's `--no-dev` flag to avoid this, so we just
      # rip out the `require-dev` section from composer.json.
      - name: Remove dev requirements
        if: ${{ !matrix.run-tests }}
        run: |
          jq 'del(."require-dev", ."autoload-dev")' composer.json > composer.json.tmp
          mv composer.json.tmp composer.json

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --no-progress --no-interaction ${{ matrix.run-tests == false && '--no-dev' || '' }}

      # If PHP >=8.4, run PHPUnit tests.
      - name: Run tests
        if: ${{ matrix.run-tests }}
        run: vendor/bin/phpunit

      # If PHP <8.4, run syntax check.
      - name: Check PHP syntax
        if: ${{ !matrix.run-tests }}
        run: find src -name '*.php' -print0 | xargs -0 -n1 php -l

      # Load the library and parse one address as a smoke test.
      - name: Test library
        if: ${{ !matrix.run-tests }}
        run: |
          php -r '
            require "vendor/autoload.php";
            $address = ( new ZeroDaHero\Normalizer() )->parse( "123 Main Street, Fall River, MA 02720" );
            echo $address, PHP_EOL;
            exit( $address ? 0 : 1 );
          '
